version: '3.1'

services:
  
  signup-db:
    image: microsoft/mssql-server-windows-express
    environment: 
      - ACCEPT_EULA=Y
    env_file:
      - db-credentials.env
    networks:
      - app-net

  signup-web:
    image: ${dockerId}/signup-web:1.3
    ports:
      - "80"
    environment:
      - HOMEPAGE_URL=http://homepage
    env_file:
      - db-credentials.env
    depends_on:
      - signup-db
      - message-queue
      - homepage
    networks:
      - app-net

  message-queue:
    image: nats:nanoserver
    networks:
      - app-net

  signup-save-handler:
    image: ${dockerId}/signup-save-handler
    env_file:
      - db-credentials.env
    depends_on:
      - signup-db
      - message-queue
    networks:
      - app-net

  elasticsearch:
    image: anoop/elasticsearch:nanoserver
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    networks:
      - app-net

  kibana:
    image: anoop/kibana:nanoserver
    ports:
      - "5601"
    depends_on:
      - elasticsearch
    networks:
      - app-net

  signup-index-handler:
    image: ${dockerId}/signup-index-handler
    depends_on:
      - elasticsearch
      - message-queue
    networks:
      - app-net

  homepage:
    image: ${dockerId}/signup-homepage
    networks:
      - app-net

networks:
  app-net:
    external:
      name: nat
